name: foursquare
description: Foursquare for Dart and Flutter, enabling location-based experiences for mobile, web, and server applications.
version: 0.1.0
homepage: https://matthewhuie.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http: ^0.12.2
  flutter:
    sdk: flutter
  sunny_dart: ^0.5.8+3

dev_dependencies:
  pedantic: ^1.9.2

dependency_overrides:
  sunny_dart:
    path: ../sunny_dart
